image: "rust:latest"

test:cargo:
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose
pages:
  script:
    - cargo doc --no-deps 
  artifacts:
    paths:
      - public
